# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs GPU-based simulator
#' 
#' @param portfolio `matrix` porfolio
#' @param n_factor `integer` number of factors
#' @param n_sim `integer` number of simulations
#' @export
g_simulate <- function(portfolio, n_factor, n_sim) {
    .Call(`_GpuExample_g_simulate`, portfolio, n_factor, n_sim)
}

#' Calculates random numbers
#' @export
rand_num <- function() {
    invisible(.Call(`_GpuExample_rand_num`))
}

#' Runs a portfolio simulation in C++
#' 
#' @param portfolio `matrix` porfolio
#' @param n_factor `integer` number of factors
#' @param n_sim `integer` number of simulations
sim <- function(portfolio, n_factor, n_sim) {
    .Call(`_GpuExample_sim`, portfolio, n_factor, n_sim)
}

#' Runs GPU-based simulator
#' 
#' @param numbers `vector` input vector
#' @param N `integer` number of samples
#' @export
xorshift_generator <- function(numbers, N) {
    .Call(`_GpuExample_xorshift_generator`, numbers, N)
}

